config/routes.rb
Rails.application.routes.draw do
  resources :add_quantity_to_line_items
  resources :line_items
  resources :carts
	root 'store#index', as: 'store_index'
  get 'store/index'
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/add_quantity_to_line_item.rb
class AddQuantityToLineItem < ApplicationRecord
end

app/controllers/add_quantity_to_line_items_controller.rb
class AddQuantityToLineItemsController < ApplicationController
  before_action :set_add_quantity_to_line_item, only: [:show, :edit, :update, :destroy]

  # GET /add_quantity_to_line_items
  # GET /add_quantity_to_line_items.json
  def index
    @add_quantity_to_line_items = AddQuantityToLineItem.all
  end

  # GET /add_quantity_to_line_items/1
  # GET /add_quantity_to_line_items/1.json
  def show
  end

  # GET /add_quantity_to_line_items/new
  def new
    @add_quantity_to_line_item = AddQuantityToLineItem.new
  end

  # GET /add_quantity_to_line_items/1/edit
  def edit
  end

  # POST /add_quantity_to_line_items
  # POST /add_quantity_to_line_items.json
  def create
    @add_quantity_to_line_item = AddQuantityToLineItem.new(add_quantity_to_line_item_params)

    respond_to do |format|
      if @add_quantity_to_line_item.save
        format.html { redirect_to @add_quantity_to_line_item, notice: 'Add quantity to line item was successfully created.' }
        format.json { render :show, status: :created, location: @add_quantity_to_line_item }
      else
        format.html { render :new }
        format.json { render json: @add_quantity_to_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /add_quantity_to_line_items/1
  # PATCH/PUT /add_quantity_to_line_items/1.json
  def update
    respond_to do |format|
      if @add_quantity_to_line_item.update(add_quantity_to_line_item_params)
        format.html { redirect_to @add_quantity_to_line_item, notice: 'Add quantity to line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @add_quantity_to_line_item }
      else
        format.html { render :edit }
        format.json { render json: @add_quantity_to_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /add_quantity_to_line_items/1
  # DELETE /add_quantity_to_line_items/1.json
  def destroy
    @add_quantity_to_line_item.destroy
    respond_to do |format|
      format.html { redirect_to add_quantity_to_line_items_url, notice: 'Add quantity to line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add_quantity_to_line_item
      @add_quantity_to_line_item = AddQuantityToLineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def add_quantity_to_line_item_params
      params.require(:add_quantity_to_line_item).permit(:quantity)
    end
end

app/helpers/add_quantity_to_line_items_helper.rb
module AddQuantityToLineItemsHelper
end

app/views/add_quantity_to_line_items/_form.html.haml
= form_with(model: add_quantity_to_line_item, local: true) do |form|
  - if add_quantity_to_line_item.errors.any?
    #error_explanation
      %h2
        = pluralize(add_quantity_to_line_item.errors.count, "error")
        prohibited this add_quantity_to_line_item from being saved:
      %ul
        - add_quantity_to_line_item.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :quantity
    = form.number_field :quantity
  .actions
    = form.submit

app/views/add_quantity_to_line_items/edit.html.haml
%h1 Editing Add Quantity To Line Item
= render 'form', add_quantity_to_line_item: @add_quantity_to_line_item
= link_to 'Show', @add_quantity_to_line_item
|
= link_to 'Back', add_quantity_to_line_items_path

app/views/add_quantity_to_line_items/index.html.haml
%p#notice= notice
%h1 Add Quantity To Line Items
%table
  %thead
    %tr
      %th Quantity
      %th{:colspan => "3"}
  %tbody
    - @add_quantity_to_line_items.each do |add_quantity_to_line_item|
      %tr
        %td= add_quantity_to_line_item.quantity
        %td= link_to 'Show', add_quantity_to_line_item
        %td= link_to 'Edit', edit_add_quantity_to_line_item_path(add_quantity_to_line_item)
        %td= link_to 'Destroy', add_quantity_to_line_item, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Add Quantity To Line Item', new_add_quantity_to_line_item_path

app/views/add_quantity_to_line_items/new.html.haml
%h1 New Add Quantity To Line Item
= render 'form', add_quantity_to_line_item: @add_quantity_to_line_item
= link_to 'Back', add_quantity_to_line_items_path

app/views/add_quantity_to_line_items/show.html.haml
%p#notice= notice
%p
  %strong Quantity:
  = @add_quantity_to_line_item.quantity
= link_to 'Edit', edit_add_quantity_to_line_item_path(@add_quantity_to_line_item)
|
= link_to 'Back', add_quantity_to_line_items_path